In [14]:
# Set env variable before import of vds_access!
import os
os.environ["WEBVIZ_VDS_HOST_ADDRESS"] = "https://server-oneseismictest-dev.playground.radix.equinor.com"

from sumo.wrapper import SumoClient


# from fmu.sumo.explorer import Explorer
# from fmu.sumo.explorer.objects.cube_collection import CubeCollection
from fmu.sumo.explorer.objects import CaseCollection

from services.vds_access.vds_access import VdsAccess
# from services.vds_access. import VdsMetadata
from services.sumo_access.seismic_access import SeismicAccess
from services.vds_access.request_types import VdsCoordinates
from services.vds_access.response_types import VdsMetadata

from src.services.sumo_access._helpers import SumoCase


import numpy as np



# Test data
case_uuid = "c619f32d-3ada-4e5e-8d3c-330f940e88f8"
realization = 0
iteration = "iter-0"
cube_tagname = "amplitude_far_time"
timestep = None
timestamp = "2018-01-01T00:00:00"
observed = False

sumo_client = SumoClient(env="prod")
case_collection = CaseCollection(sumo_client).filter(uuid=case_uuid) # Existing working case
case = case_collection[0]

sumo_case = await SumoCase.from_case_uuid(sumo_client.authenticate(), case_uuid=case_uuid)

# Setup
seismic_access = SeismicAccess(sumo_client=sumo_client, case=case, case_uuid=case_uuid, iteration_name=iteration)
vds_handle = await seismic_access.get_vds_handle(seismic_attribute=cube_tagname,realization=realization, time_or_interval_str=timestamp)
vds_access = VdsAccess(sas_token=vds_handle.sas_token, vds_url=vds_handle.vds_url)

num_polyline_points = 10
x_points = np.linspace(462799.467, 464923.32, num_polyline_points)
y_points = np.linspace(5929653.056, 5933656.999, num_polyline_points)

[
    flattened_fence_traces_array,
    num_traces,
    num_trace_samples,
]  = await vds_access.get_flattened_fence_traces_array_and_metadata(coordinates=VdsCoordinates(x_points=x_points, y_points=y_points))
[
    fence_traces_array,
    _num_traces,
    _num_trace_samples,
]  = await vds_access.get_fence_traces_array_and_metadata(coordinates=VdsCoordinates(x_points=x_points, y_points=y_points))


meta: VdsMetadata = await vds_access.get_metadata()
if len(meta.axis) != 3:
    raise ValueError(f"Expected 3 axes, got {len(meta.axis)}")
depth_axis_meta = meta.axis[2]
print(meta)
print(f'Vds Access coordinate system: {meta.crs}')

# coordinate_system = await sumo_case.get_coordinate_system_identifier()
# print(f'Sumo case coordinate system: {coordinate_system}')

print(f'Flattened fence traces array: {flattened_fence_traces_array}')
print(f'Number of traces: {num_traces}')
print(f'Number of samples in trace: {num_trace_samples}')

print("\n")
print(f'Number of fence traces: {len(fence_traces_array)}')
print(f'Length of fence traces: {len(fence_traces_array[0])}')
print(f'Shape: Number of traces: {fence_traces_array.shape[0]}')
print(f'Shape: Number of fence samples: {fence_traces_array.shape[1]}')
print(f'Fence traces array: {fence_traces_array}')
print(f'First trace: {fence_traces_array[0]}')









axis=[VdsAxis(annotation='Inline', max=217.0, min=0.0, samples=218, unit='unitless'), VdsAxis(annotation='Crossline', max=137.0, min=0.0, samples=138, unit='unitless'), VdsAxis(annotation='Sample', max=1999.0, min=1500.0, samples=500, unit='ms')] boundingBox=VdsBoundingBox(cdp=[[461484.34, 5926563.2], [456083.37, 5936006.48], [462069.5080733945, 5939430.173027524], [467470.4780733945, 5929986.8930275235]], ij=[[0.0, 0.0], [217.0, 0.0], [217.0, 137.0], [0.0, 137.0]], ilxl=[[0.0, 0.0], [217.0, 0.0], [217.0, 137.0], [0.0, 137.0]]) crs=''
Vds Access coordinate system: 
Flattened fence traces array: [0. 0. 0. ... 0. 0. 0.]
Number of traces: 10
Number of samples in trace: 500


Number of fence traces: 10
Length of fence traces: 500
Shape: Number of traces: 10
Shape: Number of fence samples: 500
Fence traces array: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
First trace: [ 0.0000000

In [21]:
## TEST ROUTER

sumo_client = SumoClient(env="prod")

from src.backend.primary.routers.seismic.router import get_fence
from src.backend.primary.routers.seismic.schemas import SeismicFencePolyline
from src.backend.auth.auth_helper import AuthHelper, AuthenticatedUser

sumo_client = SumoClient(env="prod")

case_uuid = "c619f32d-3ada-4e5e-8d3c-330f940e88f8"
realization = 0
iteration = "iter-0"
cube_tagname = "amplitude_far_time"
timestep = None
timestamp = "2018-01-01T00:00:00"
observed = False

x_points = [463156.911, 463564.402, 463637.925, 463690.658, 463910.452]
y_points = [5929542.294, 5931057.803, 5931184.235, 5931278.837, 5931688.122]

x_points = [463156.911, 463564.402, 463637.925, 463690.658]
y_points = [5929542.294, 5931057.803, 5931184.235, 5931278.837]

#authenticated_user = AuthHelper.get_authenticated_user()

#seismic_fence = await get_seismic_fence(authenticated_user, case_uuid, iteration, realization, cube_tagname, timestamp, observed, SeismicFencePolyline(x_points=x_points, y_points=y_points))

In [24]:
import numpy as np
from typing import List

test_array = [[1,2,3],[4,5,6],[7,8,9],[10, 11, 12]]
test_bytes = np.array(test_array).tobytes()

test_array_np_3x3 = np.ndarray(buffer=test_bytes, dtype=np.int64, shape=(4,3))
test_array_np_1x9 = np.ndarray(buffer=test_bytes, dtype=np.int64, shape=(1,12), order="C")

test_flattened_C = test_array_np_3x3.flatten(order="C")
test_flattened_F = test_array_np_3x3.flatten(order="F")
print(test_array)
print(test_array_np_3x3)
print(test_array_np_1x9)
print(test_flattened_C)
print(test_flattened_F)

# Test code:
test_array = [["t11","t12","t13"], ["t21","t22","t23"], ["t31","t32","t33"]]
test_flattened_array_C = np.asarray(test_array).ravel(order='C')
test_flattened_array_F = np.asarray(test_array).ravel(order='F')
print(test_array)
print(test_flattened_array_C)
print(test_flattened_array_F)


[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  4  7 10  2  5  8 11  3  6  9 12]
[['t11', 't12', 't13'], ['t21', 't22', 't23'], ['t31', 't32', 't33']]
['t11' 't12' 't13' 't21' 't22' 't23' 't31' 't32' 't33']
['t11' 't21' 't31' 't12' 't22' 't32' 't13' 't23' 't33']
